### ISSUE TITLE
[BugFix] Error when executed by docker-compose

### ISSUE THREAD

**Issue by paulopaquielli** [devfsa/overflow-news#23]
```
worker_1  | TypeError: Path must be a string. Received undefined
worker_1  |     at assertPath (path.js:28:11)
worker_1  |     at Object.join (path.js:1236:7)
worker_1  |     at Object.<anonymous> (/usr/src/app/src/worker.js:9:15)
worker_1  |     at Module._compile (module.js:652:30)
worker_1  |     at loader (/usr/src/app/node_modules/babel-register/lib/node.js:144:5)
worker_1  |     at Object.require.extensions.(anonymous function) [as .js] (/usr/src/app/node_modules/babel-register/lib/node.js:154:7)
worker_1  |     at Module.load (module.js:565:32)
worker_1  |     at tryModuleLoad (module.js:505:12)
worker_1  |     at Function.Module._load (module.js:497:3)
worker_1  |     at Function.Module.runMain (module.js:693:10)
worker_1  |     at startup (bootstrap_node.js:188:16)
worker_1  |     at bootstrap_node.js:609:3
worker_1  | [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by di3goleite** [comment]
Thank you @PauloPaquielli but there is a problem with this PR.
We have some obscure code at `src/bootstrap/env.js` file. This code loads the environment variables located in this dot env file: `.env`. The `src/bootstrap/env.js` file is called in both `src/server.js` and `src/worker.js` at the line 1.

So, I think we should do some code refactoring here because if we do it in the `docker-compose.yml` file too this will load the environment variables twice (or more).

What do you guys think?

**Comment by rafaelverger** [comment]
Hmm.. there's no problem on setting env vars twice (or more than two times) it will get the latest value... if they're all the same, so no problem on that
